runtime: go122
env_variables:
  APP_ENV: production
handlers:
- url: /static
  static_dir: static
- url: /demos
  static_dir: demos
- url: /
  static_files: output/index.html
  upload: output/index.html
- url: /(.*)/
  static_files: output/\1/index.html
  upload: output/(.*)
- url: /(.*)
  static_files: output/\1/index.html
  upload: output/(.*)
- url: .*
  script: auto
