runtime: go122
env_variables:
  APP_ENV: production
handlers:
- url: /static
  static_dir: static

- url: /(.*)/
  static_files: output/\1/index.html
  upload: output/(.*)/index.html

- url: /([^\.]*)
  static_files: output/\1/index.html
  upload: output/(.*)/index.html

- url: /([^\.]*\..*)
  static_files: output/\1
  upload: output/(.*)
