runtime: go122
env_variables:
  APP_ENV: production
handlers:
- url: /static
  static_dir: static

- url: /demos/([^/]+)/$
  static_files: demos/\1/index.html
  upload: demos/.*/index\.html

- url: /demos/([^/]+)/(.+)
  static_files: demos/\1/\2
  upload: demos/.*/.*

- url: /demos/([^/]+)$
  static_files: demos/\1/index.html
  upload: demos/.*/index\.html

- url: /
  static_files: output/index.html
  upload: output/index.html
- url: /(.*)/
  static_files: output/\1/index.html
  upload: output/(.*)
- url: /(.*)
  static_files: output/\1/index.html
  upload: output/(.*)
- url: .*
  script: auto
