runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /
  static_files: server/pages/index.html
  upload: server/pages/index.html

- url: /(.*)
  static_files: server/pages/\1.html
  upload: server/pages/(.*)
